/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-04-06 15:01:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.front;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 cdn -->\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\t\tintegrity=\"sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- right/left 방향이미지 적용을 위한 cdn-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/sidebar.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 공통 css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "form/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<!-- 슬라이드 이미지 영역 -->\r\n");
      out.write("\t<section id=\"testimonial\" class=\"section-100\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"testimonial-view\">\r\n");
      out.write("\t\t\t\t<h5><b>TOP10 인기 포트폴리오(21.03~21.04)</b></h5>\r\n");
      out.write("\t\t\t\t<div class=\"owl-carousel\">\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"testimonial-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/user.jpg\" alt=\"\" class=\"user-img mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"mb-0\"><b>&nbsp;&nbsp;hyojun9292</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted mb-0\" style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"text-decoration: underline;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t92.10.24\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;(N년차)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span style=\"color:black\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>프론트 개발</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-2\" style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>· 주 사용 언어</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#6c757d;\">REACT ANGULAR JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 대표 이력</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) ㅇㅇ회사 근무\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) KH학원\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 개발 프로젝트</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 요리 소개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사이트 개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 무언가를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개발개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 종료 -->\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"testimonial-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/user.jpg\" alt=\"\" class=\"user-img mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"mb-0\"><b>&nbsp;&nbsp;hyojun9292</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted mb-0\" style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-decoration: underline;\">92.10.24</span><span>&nbsp;(N년차)</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span style=\"color:black\"><b>프론트 개발</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-2\" style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>· 주 사용 언어</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#6c757d;\">REACT ANGULAR JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 대표 이력</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) ㅇㅇ회사 근무\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) KH학원\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 개발 프로젝트</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 요리 소개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사이트 개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 무언가를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개발개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 종료 -->\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"testimonial-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/user.jpg\" alt=\"\" class=\"user-img mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"mb-0\"><b>&nbsp;&nbsp;hyojun9292</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted mb-0\" style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-decoration: underline;\">92.10.24</span><span>&nbsp;(N년차)</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span style=\"color:black\"><b>프론트 개발</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-2\" style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>· 주 사용 언어</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#6c757d;\">REACT ANGULAR JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 대표 이력</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) ㅇㅇ회사 근무\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) KH학원\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 개발 프로젝트</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 요리 소개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사이트 개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 무언가를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개발개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 종료 -->\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"testimonial-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/user.jpg\" alt=\"\" class=\"user-img mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"mb-0\"><b>&nbsp;&nbsp;hyojun9292</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted mb-0\" style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-decoration: underline;\">92.10.24</span><span>&nbsp;(N년차)</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span style=\"color:black\"><b>프론트 개발</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-2\" style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>· 주 사용 언어</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#6c757d;\">REACT ANGULAR JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 대표 이력</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) ㅇㅇ회사 근무\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) KH학원\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 개발 프로젝트</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 요리 소개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사이트 개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 무언가를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개발개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 종료 -->\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"testimonial-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/user.jpg\" alt=\"\" class=\"user-img mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"mb-0\"><b>&nbsp;&nbsp;hyojun9292</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted mb-0\" style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-decoration: underline;\">92.10.24</span><span>&nbsp;(N년차)</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;<span style=\"color:black\"><b>프론트 개발</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-2\" style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>· 주 사용 언어</b><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#6c757d;\">REACT ANGULAR JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-bottom: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 대표 이력</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) ㅇㅇ회사 근무\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) KH학원\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0;\"><b>· 최근 개발 프로젝트</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 요리 소개\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사이트 개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"font-size: 8px; margin:0; padding:0; color:#6c757d;\">(2018.06~2020.03) 무언가를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개발개발</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로필 종료 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- 슬라이드 이미지 영역 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 게시판 -->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<div class=\"container w-75\">\r\n");
      out.write("        <div class=\"bg-light\" style=\"text-align: center\">\r\n");
      out.write("          <h5>공지사항</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("          <table class=\"table table-striped table-sm\" style='text-align: center' >\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("            <th class=\"col-lg-1\">글번호</th>\r\n");
      out.write("            <th class=\"col-lg-4\">제목</th>\r\n");
      out.write("            <th class=\"col-lg-2\">작성자</th>\r\n");
      out.write("            <th class=\"col-lg-2\">일자</th>\r\n");
      out.write("            <th class=\"col-lg-2\">조회수</th>\r\n");
      out.write("            <th class=\"col-lg-1\">추천수</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr>\r\n");
      out.write("            <td>1</td>\r\n");
      out.write("            <td>프로젝트어쩌구 저쩌구</td>\r\n");
      out.write("            <td>홍길동</td>\r\n");
      out.write("            <td>2020-00-00</td>\r\n");
      out.write("            <td>10</td>\r\n");
      out.write("            <td>5</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("            <td>2</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("            <td>3</td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"../js/sidebar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "form/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
